// Generated by scripts/gen-integration-manifest.ts. Do not edit manually.
import type { IntegrationModule } from '../lib/registry.js';

import * as integration0 from './dotnet/index.js';
import * as integration1 from './elixir/index.js';
import * as integration2 from './go/index.js';
import * as integration3 from './kotlin/index.js';
import * as integration4 from './nextjs/index.js';
import * as integration5 from './node/index.js';
import * as integration6 from './php/index.js';
import * as integration7 from './php-laravel/index.js';
import * as integration8 from './python/index.js';
import * as integration9 from './react/index.js';
import * as integration10 from './react-router/index.js';
import * as integration11 from './ruby/index.js';
import * as integration12 from './sveltekit/index.js';
import * as integration13 from './tanstack-start/index.js';
import * as integration14 from './vanilla-js/index.js';

export const integrationModules = {
  dotnet: integration0,
  elixir: integration1,
  go: integration2,
  kotlin: integration3,
  nextjs: integration4,
  node: integration5,
  php: integration6,
  'php-laravel': integration7,
  python: integration8,
  react: integration9,
  'react-router': integration10,
  ruby: integration11,
  sveltekit: integration12,
  'tanstack-start': integration13,
  'vanilla-js': integration14,
} satisfies Record<string, IntegrationModule>;
