// Generates the Homebrew formula (dist/homebrew/workos.rb) from the already-built
// platform binaries in dist/ (release asset names). The release workflow pushes
// the result to the workos/homebrew-tap repo, so `brew install workos/tap/workos`
// tracks each GitHub release.
//
// Homebrew downloads the raw release binary (no tarball) and installs it as
// `workos`; the sha256 for each platform is computed here from the same
// artifacts the GitHub release ships, so the tap can never drift from the bits.
//
// WORKOS_HOMEBREW_VERSION  version to stamp; defaults to the repo package.json
//                          version. Prerelease versions (containing `-`) are
//                          rejected — brew users track stable only.
import { createHash } from 'node:crypto';
import { existsSync, mkdirSync, rmSync } from 'node:fs';
import { readFile, writeFile } from 'node:fs/promises';
import { join } from 'node:path';

const projectRoot = join(import.meta.dirname, '..');
const distDir = join(projectRoot, 'dist');
const outDir = join(distDir, 'homebrew');

const rootPackageJson = JSON.parse(await readFile(join(projectRoot, 'package.json'), 'utf8')) as {
  version: string;
  license?: string;
};
const version = process.env.WORKOS_HOMEBREW_VERSION ?? rootPackageJson.version;
if (!/^\d+\.\d+\.\d+$/.test(version)) {
  throw new Error(`Refusing to generate a Homebrew formula for non-stable version: ${version}`);
}

// Hardcoded rather than reused from package.json: Homebrew's audit wants a desc
// with no leading article and without the formula name, unlike the npm-facing
// package description.
const DESCRIPTION = 'Install AuthKit integrations and manage WorkOS resources';
const LICENSE = rootPackageJson.license ?? 'MIT';
const HOMEPAGE = 'https://github.com/workos/cli';
const DOWNLOAD_BASE = `https://github.com/workos/cli/releases/download/v${version}`;

// Homebrew macOS + Linuxbrew (glibc) only — no musl or Windows. `on_arm`/
// `on_intel` blocks map straight onto these four release assets.
const PLATFORMS: Array<{ os: 'macos' | 'linux'; cpu: 'arm' | 'intel'; asset: string }> = [
  { os: 'macos', cpu: 'arm', asset: 'workos-darwin-arm64' },
  { os: 'macos', cpu: 'intel', asset: 'workos-darwin-x64' },
  { os: 'linux', cpu: 'arm', asset: 'workos-linux-arm64' },
  { os: 'linux', cpu: 'intel', asset: 'workos-linux-x64' },
];

const missing = PLATFORMS.filter((p) => !existsSync(join(distDir, p.asset)));
if (missing.length > 0) {
  throw new Error(`Missing platform binaries in dist/: ${missing.map((p) => p.asset).join(', ')}`);
}

async function sha256(asset: string): Promise<string> {
  return createHash('sha256')
    .update(await readFile(join(distDir, asset)))
    .digest('hex');
}

const shas = new Map<string, string>();
for (const platform of PLATFORMS) {
  shas.set(platform.asset, await sha256(platform.asset));
}

// One `on_arm`/`on_intel` stanza; each pins the URL + sha and installs the raw
// binary (named after the URL's basename) as `workos`.
function stanza(cpu: 'arm' | 'intel', asset: string): string {
  return [
    `    on_${cpu} do`,
    `      url "${DOWNLOAD_BASE}/${asset}"`,
    `      sha256 "${shas.get(asset)}"`,
    '',
    '      def install',
    `        bin.install "${asset}" => "workos"`,
    '      end',
    '    end',
  ].join('\n');
}

const macos = PLATFORMS.filter((p) => p.os === 'macos');
const linux = PLATFORMS.filter((p) => p.os === 'linux');

const formula = `# typed: false
# frozen_string_literal: true

# Generated by workos/cli release automation (scripts/gen-homebrew-formula.ts).
# DO NOT EDIT — changes are overwritten on the next release.
class Workos < Formula
  desc "${DESCRIPTION}"
  homepage "${HOMEPAGE}"
  version "${version}"
  license "${LICENSE}"

  on_macos do
${macos.map((p) => stanza(p.cpu, p.asset)).join('\n')}
  end

  on_linux do
${linux.map((p) => stanza(p.cpu, p.asset)).join('\n')}
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/workos --version")
  end
end
`;

rmSync(outDir, { recursive: true, force: true });
mkdirSync(outDir, { recursive: true });
await writeFile(join(outDir, 'workos.rb'), formula);

console.log(`Generated Homebrew formula (v${version}) at ${join(outDir, 'workos.rb')}:`);
for (const platform of PLATFORMS) {
  console.log(`  ${platform.os}/${platform.cpu}  ${platform.asset}  ${shas.get(platform.asset)}`);
}
