import { existsSync } from 'node:fs';
import { readdir, writeFile } from 'node:fs/promises';
import { join } from 'node:path';

const projectRoot = join(import.meta.dirname, '..');
const integrationsDir = join(projectRoot, 'src', 'integrations');
const manifestPath = join(integrationsDir, '_manifest.ts');

const entries = await readdir(integrationsDir, { withFileTypes: true });
const integrationNames = entries
  // A directory without an index.ts (scratch dir, editor artifact) must not
  // produce a broken static import that fails the whole build.
  .filter(
    (entry) =>
      entry.isDirectory() && !entry.name.startsWith('_') && existsSync(join(integrationsDir, entry.name, 'index.ts')),
  )
  .map((entry) => entry.name)
  .sort();

const imports = integrationNames
  .map((name, index) => `import * as integration${index} from './${name}/index.js';`)
  .join('\n');
const modules = integrationNames
  .map((name, index) => {
    const key = /^[A-Za-z_$][\w$]*$/.test(name) ? name : `'${name}'`;
    return `  ${key}: integration${index},`;
  })
  .join('\n');

const manifest = `// Generated by scripts/gen-integration-manifest.ts. Do not edit manually.
import type { IntegrationModule } from '../lib/registry.js';

${imports}

export const integrationModules = {
${modules}
} satisfies Record<string, IntegrationModule>;
`;

await writeFile(manifestPath, manifest);
