/**
 * Generate src/commands/api/embedded-spec.ts — the offline fallback copy of the
 * WorkOS OpenAPI spec, baked into the source so it survives `bun build --compile`
 * (a single-file binary has no node_modules to require.resolve at runtime).
 *
 * Run after bumping @workos/openapi-spec:  bun run gen:embedded-spec
 * CI freshness:  bun run scripts/gen-embedded-spec.ts --check
 */
import { createRequire } from 'node:module';
import { readFile, writeFile } from 'node:fs/promises';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const require = createRequire(import.meta.url);
const specYaml = await readFile(require.resolve('@workos/openapi-spec/spec'), 'utf-8');
const pkg = JSON.parse(await readFile(require.resolve('@workos/openapi-spec/package.json'), 'utf-8')) as {
  version: string;
};

const outPath = join(dirname(fileURLToPath(import.meta.url)), '..', 'src', 'commands', 'api', 'embedded-spec.ts');
const generated = `// @generated by scripts/gen-embedded-spec.ts — DO NOT EDIT.
// Offline fallback for the WorkOS OpenAPI spec (package v${pkg.version}).
// Regenerate with: bun run gen:embedded-spec
export const EMBEDDED_OPENAPI_SPEC_VERSION = ${JSON.stringify(pkg.version)};
export const EMBEDDED_OPENAPI_SPEC = ${JSON.stringify(specYaml)};
`;

if (process.argv.includes('--check')) {
  const current = await readFile(outPath, 'utf-8').catch(() => '');
  if (current !== generated) {
    console.error('embedded-spec.ts is stale. Run: bun run gen:embedded-spec');
    process.exit(1);
  }
  console.log(`embedded-spec.ts is up to date (spec v${pkg.version}).`);
} else {
  await writeFile(outPath, generated);
  console.log(`Wrote ${outPath} (spec v${pkg.version}, ${specYaml.length} bytes).`);
}
