import { createHash } from 'node:crypto';
import { readFileSync } from 'node:fs';
import { mkdir, readFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

// Same musl detection the runtime's isMuslRuntime() and the napi-rs loaders use:
// Alpine's ldd is a musl script, and glibc processes report a glibcVersionRuntime
// header. Without this, a `bun install` on Alpine (postinstall runs generate)
// would pin the glibc SDK package while the runtime demands the musl one.
function isMuslHost(): boolean {
  if (process.platform !== 'linux') return false;
  try {
    if (readFileSync('/usr/bin/ldd', 'utf8').includes('musl')) return true;
  } catch {
    // No readable /usr/bin/ldd — fall through to the process report.
  }
  try {
    const report = process.report?.getReport() as { header?: { glibcVersionRuntime?: string } } | undefined;
    if (report?.header) return !report.header.glibcVersionRuntime;
  } catch {
    // Report unavailable — assume glibc.
  }
  return false;
}

const projectRoot = join(import.meta.dirname, '..');
const manifestPath = join(projectRoot, 'src', 'generated', 'agent-sdk-manifest.ts');
const hostTarget = `bun-${process.platform}-${process.arch}${isMuslHost() ? '-musl' : ''}`;
const requestedTarget = process.env.WORKOS_BUILD_TARGET ?? hostTarget;
const normalizedTarget = requestedTarget
  .replace(/^bun-/, '')
  .replace(/-baseline$/, '')
  .replace(/-modern$/, '');
const isMusl = normalizedTarget.endsWith('-musl');
const [targetOs, targetArch] = normalizedTarget.replace(/-musl$/, '').split('-');

const packageOs = targetOs === 'windows' ? 'win32' : targetOs;
if (!packageOs || !targetArch || !['darwin', 'linux', 'win32'].includes(packageOs)) {
  throw new Error(`Unsupported WorkOS binary target for the Agent SDK: ${requestedTarget}`);
}

const packageTarget = `${packageOs}-${targetArch}${isMusl ? '-musl' : ''}`;
const packageName = `@anthropic-ai/claude-agent-sdk-${packageTarget}`;
const packageJsonPath = fileURLToPath(import.meta.resolve(`${packageName}/package.json`));
const packageRoot = dirname(packageJsonPath);
const packageJson = JSON.parse(await readFile(packageJsonPath, 'utf8')) as { version?: unknown };
const executableName = packageOs === 'win32' ? 'claude.exe' : 'claude';
const executablePath = join(packageRoot, executableName);

if (typeof packageJson.version !== 'string') {
  throw new Error(`Could not determine the installed ${packageName} version`);
}

const executable = await readFile(executablePath);
const executableSha256 = createHash('sha256').update(executable).digest('hex');
const tarballBasename = packageName.split('/')[1];
const tarballUrl = `https://registry.npmjs.org/${packageName}/-/${tarballBasename}-${packageJson.version}.tgz`;

await mkdir(dirname(manifestPath), { recursive: true });

const manifest = `// Generated by scripts/gen-agent-sdk-manifest.ts. Do not edit manually.
// The native Agent SDK executable is NOT embedded in the compiled binary: it is
// downloaded on first agent use, pinned to this exact version and checksum.
export const AGENT_SDK_TARGET = ${JSON.stringify(packageTarget)};
export const AGENT_SDK_VERSION = ${JSON.stringify(packageJson.version)};
export const AGENT_SDK_PACKAGE = ${JSON.stringify(packageName)};
export const AGENT_SDK_TARBALL_URL = ${JSON.stringify(tarballUrl)};
export const AGENT_SDK_EXECUTABLE_NAME = ${JSON.stringify(executableName)};
export const AGENT_SDK_EXECUTABLE_SIZE = ${executable.byteLength};
export const AGENT_SDK_EXECUTABLE_SHA256 = ${JSON.stringify(executableSha256)};
`;

await Bun.write(manifestPath, manifest);
