import { mkdir, readdir, readFile, stat } from 'node:fs/promises';
import { dirname, join, relative, sep } from 'node:path';
import { fileURLToPath } from 'node:url';

const projectRoot = join(import.meta.dirname, '..');
const generatedDir = join(projectRoot, 'src', 'generated');
const manifestPath = join(generatedDir, 'skills-manifest.ts');
const packageEntry = fileURLToPath(import.meta.resolve('@workos/skills'));
const packageRoot = dirname(dirname(packageEntry));
const pluginsDir = join(packageRoot, 'plugins');
const packageJson = JSON.parse(await readFile(join(packageRoot, 'package.json'), 'utf8')) as { version?: unknown };

await mkdir(generatedDir, { recursive: true });

if (typeof packageJson.version !== 'string') {
  throw new Error('Could not determine the installed @workos/skills version');
}

async function collectFiles(dir: string): Promise<string[]> {
  const entries = await readdir(dir, { withFileTypes: true });
  const files = await Promise.all(
    entries.map(async (entry) => {
      const path = join(dir, entry.name);
      if (entry.isDirectory()) return collectFiles(path);
      if (entry.isFile()) return [path];
      return [];
    }),
  );
  return files.flat();
}

const files = (await collectFiles(pluginsDir)).sort();
const imports: string[] = [];
const assets: string[] = [];

for (const [index, path] of files.entries()) {
  const info = await stat(path);
  const relPath = relative(pluginsDir, path).split(sep).join('/');
  // TypeScript does not model Bun's `file` import attribute, but Bun embeds
  // each asset and replaces the import with its path in the standalone binary.
  imports.push(`// @ts-expect-error Bun file imports support arbitrary asset extensions`);
  imports.push(`import asset${index} from ${JSON.stringify(path)} with { type: 'file' };`);
  assets.push(
    `  { relPath: ${JSON.stringify(relPath)}, embedded: asset${index}, executable: ${Boolean(info.mode & 0o111)} },`,
  );
}

const manifest = `// Generated by scripts/gen-skills-manifest.ts. Do not edit manually.
${imports.join('\n')}

export const BUNDLED_SKILLS_VERSION = ${JSON.stringify(packageJson.version)};

export const skillsAssets: ReadonlyArray<{
  relPath: string;
  embedded: string;
  executable: boolean;
}> = [
${assets.join('\n')}
];
`;

await Bun.write(manifestPath, manifest);
