import { mkdir, readFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { satisfies, valid } from 'semver';

// Dependencies the compiled CLI can update independently of its own releases.
// Each package publishes a self-contained ESM bundle at dist/bundle.js
// (exports subpath `./bundle`), plus any sidecar files the bundle resolves
// relative to itself at runtime (migrations' worker.js is loaded via
// `path.join(__dirname, 'worker.js')`, so it must be co-located). The CLI
// downloads the newest registry version inside the range baked here and
// imports it in place of the compiled-in module (see src/lib/runtime-assets.ts).
// Ranges come straight from package.json so a runtime download can never
// drift past what the compiled-in types were written against, and the version
// installed in node_modules at build time — the one Bun compiles into the
// binary — is baked alongside so the CLI only ever runs versions strictly
// newer than what it already ships. The download cache is shared by every CLI
// install on a machine; without that floor an older cached bundle could
// silently downgrade a newer CLI.
//
// `files` are tarball paths inside `package/`; the FIRST one is the ESM
// entrypoint the CLI imports.
const RUNTIME_DEP_PACKAGES: Record<string, { npmPackage: string; files: string[] }> = {
  migrations: { npmPackage: '@workos/migrations', files: ['dist/bundle.js', 'dist/worker.js'] },
  emulate: { npmPackage: '@workos/emulate', files: ['dist/bundle.js'] },
};

const projectRoot = join(import.meta.dirname, '..');
const manifestPath = join(projectRoot, 'src', 'generated', 'runtime-deps-manifest.ts');

const packageJson = JSON.parse(await readFile(join(projectRoot, 'package.json'), 'utf8')) as {
  dependencies?: Record<string, string>;
};

const entries: string[] = [];
for (const [name, { npmPackage, files }] of Object.entries(RUNTIME_DEP_PACKAGES)) {
  const range = packageJson.dependencies?.[npmPackage];
  if (typeof range !== 'string') {
    throw new Error(`${npmPackage} must be a package.json dependency to be a runtime dep`);
  }
  // Direct dependencies are hoisted to the top-level node_modules, and the
  // package's own exports map may not expose ./package.json to import.meta.resolve.
  const installedPackageJsonPath = join(projectRoot, 'node_modules', npmPackage, 'package.json');
  const installed = JSON.parse(await readFile(installedPackageJsonPath, 'utf8')) as { version?: unknown };
  const bundledVersion = installed.version;
  if (typeof bundledVersion !== 'string' || valid(bundledVersion) === null) {
    throw new Error(`Could not determine the installed ${npmPackage} version from ${installedPackageJsonPath}`);
  }
  if (!satisfies(bundledVersion, range)) {
    throw new Error(
      `Installed ${npmPackage}@${bundledVersion} does not satisfy the package.json range ${range}; run bun install`,
    );
  }
  entries.push(
    `  ${JSON.stringify(name)}: {`,
    `    npmPackage: ${JSON.stringify(npmPackage)},`,
    `    range: ${JSON.stringify(range)},`,
    `    bundledVersion: ${JSON.stringify(bundledVersion)},`,
    `    files: [${files.map((file) => JSON.stringify(file)).join(', ')}],`,
    `  },`,
  );
}

const manifest = `// Generated by scripts/gen-runtime-deps-manifest.ts. Do not edit manually.
// Runtime-downloadable dependency bundles: resolved against these baked semver
// ranges from the npm registry on use (only versions newer than the one
// compiled into this binary), integrity-verified, cached under
// ~/.workos/cache/<name>/, and imported in place of the compiled-in module.
// See src/lib/runtime-assets.ts.
export type RuntimeDepManifestEntry = {
  /** npm package that publishes the bundle. */
  npmPackage: string;
  /** Semver range baked at CLI build time (mirrors package.json). */
  range: string;
  /**
   * Version compiled into this binary (the one installed at build time). Only
   * in-range versions strictly newer than this are ever downloaded or run, so
   * a download cache shared with an older CLI can never downgrade this one.
   */
  bundledVersion: string;
  /**
   * Files to extract from the tarball, as paths inside \`package/\`. The FIRST
   * is the ESM entrypoint to import; the rest are sidecars the bundle resolves
   * relative to itself and are installed alongside it.
   */
  files: readonly string[];
};

export const RUNTIME_DEPS = {
${entries.join('\n')}
} as const satisfies Record<string, RuntimeDepManifestEntry>;

export type RuntimeDepName = keyof typeof RUNTIME_DEPS;
`;

await mkdir(dirname(manifestPath), { recursive: true });
await Bun.write(manifestPath, manifest);
