#!/usr/bin/env bash
#
# Wizard: run the branch-vs-main parity smoke test (scripts/parity-smoke.ts).
# Generated by the /wizard skill.
#
# Walks you through the manual prereqs — dashboard login, API key, env
# alignment, optional per-team flag — then runs the parity test and shows
# how to read it. Re-runnable; values already saved in .env.local are kept.
#
# Run:  bash scripts/wizard-parity-smoke.sh
#        (or)  chmod +x scripts/wizard-parity-smoke.sh && ./scripts/wizard-parity-smoke.sh

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()
WRITTEN_SECRET=()
SKIPPED=()

_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

say()  { printf '  %s\n' "$1"; }
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES
# ──────────────────────────────────────────────────────────────────────────

# The parity script reads WORKOS_API_KEY + PARITY_ENV_ID from the environment.
# .env.local is gitignored (see .gitignore) — safe place for the API key.
ENV_FILE=".env.local"
REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
BRANCH_BIN=(bun "$REPO/src/bin.ts")

TOTAL_STAGES=6

banner "Run the parity smoke test (branch vs ../main)"

# ── Stage 1: prereqs ─────────────────────────────────────────────────────
stage "Prereqs: ../main checkout + generated manifest"
say "The parity test runs shared commands on this branch and on ../main."
if [[ -f "$REPO/../main/src/bin.ts" ]] && grep -q '"workos"' "$REPO/../main/package.json" 2>/dev/null; then
  note "ok: ../main is a workos CLI checkout"
else
  warn "../main/src/bin.ts not found or not the workos CLI."
  note "Fix: place a main checkout at ../main (git worktree add ../main main),"
  note "or set PARITY_MAIN_BIN when you run the wizard's final stage."
  pause "Press Enter once that's in place (Ctrl-C to abort)"
fi
if [[ -f "$REPO/src/generated/skills-manifest.ts" ]]; then
  note "ok: generated skills manifest present"
else
  warn "src/generated/skills-manifest.ts is missing — generating it now."
  if bun run scripts/gen-skills-manifest.ts >/dev/null 2>&1; then
    note "ok: generated skills manifest"
  else
    warn "gen-skills-manifest failed; run it manually: bun run scripts/gen-skills-manifest.ts"
  fi
fi
pause "Press Enter to continue"

# ── Stage 2: dashboard login ─────────────────────────────────────────────
stage "Log in to the CLI (dashboard OAuth session)"
say "This branch's migrated + new commands authenticate with your dashboard"
say "session (OAuth bearer), not an API key. Log in now — a browser opens"
say "for the device-flow approval."
say ""
say "If you're already logged in, this is a no-op."
pause "Press Enter to run: ${BRANCH_BIN[*]} auth login"
"${BRANCH_BIN[@]}" auth login || true
pause "Press Enter once login is done"

# ── Stage 3: API key ─────────────────────────────────────────────────────
stage "Get a WorkOS API key for the target environment"
say "main's REST resource commands (and both sides' REST leftovers) use an"
say "environment-scoped API key. Grab one for the environment you want to"
say "test against — it must be the SAME env your dashboard session targets."
open_url "https://dashboard.workos.com"
step "Pick the target environment in the top switcher."
step "Go to Developers → API Keys."
step "Reveal the test/secret key (starts sk_) and copy it."
ask_secret WORKOS_API_KEY "Paste the API key:"
write_env WORKOS_API_KEY "$WORKOS_API_KEY"
pause "Press Enter to continue"

# ── Stage 4: align environments ──────────────────────────────────────────
stage "Confirm the active environment matches"
say "The branch's GraphQL commands target your session's active environment."
say "Here's what that is right now:"
if PARITY_ENV_ID=$(_existing PARITY_ENV_ID || true); [[ -n "$PARITY_ENV_ID" ]]; then
  note "PARITY_ENV_ID already pinned in .env.local → $PARITY_ENV_ID"
fi
ACTIVE_ENV=$( "${BRANCH_BIN[@]}" whoami --json 2>/dev/null \
  | sed -n 's/.*"environment"[[:space:]]*:[[:space:]]*{[^}]*"id"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' \
  | head -n1 ) || true
if [[ -n "$ACTIVE_ENV" ]]; then
  note "active environment id (from whoami): $ACTIVE_ENV"
else
  warn "couldn't read the active env id from whoami; you may need to pin PARITY_ENV_ID by hand."
fi
say ""
say "Is that the same environment your API key belongs to?"
if confirm "Active env matches the API key's env?"; then
  note "good — no PARITY_ENV_ID needed; both sides will target the same env."
else
  say "Pin PARITY_ENV_ID to the env the API key belongs to."
  say "Find that env's id (env_...) in the dashboard, or run:"
  say "  ${BRANCH_BIN[*]} env switch <name>   # then re-run this stage"
  ask PARITY_ENV_ID "Paste the environment id (env_…), or Enter to skip:"
  if [[ -n "$PARITY_ENV_ID" ]]; then
    write_env PARITY_ENV_ID "$PARITY_ENV_ID"
  else
    warn "skipped — the CONTROL checks will likely flag an env mismatch."
  fi
fi
pause "Press Enter to continue"

# ── Stage 5: optional per-team flag ──────────────────────────────────────
stage "Optional: enable the per-team GraphQL flag"
say "Two branch-only commands (project list, feature-flag list) are gated by"
say "the LaunchDarkly flag 'dashboard-oauth-bearer-graphql', evaluated per"
say "team. If your team isn't targeted, they return exit 4 (AUTH) — which the"
say "parity report shows as AUTH, not FAIL."
say ""
say "This is a LaunchDarkly action only you can perform."
if confirm "Do you want those two commands to pass (enable the flag)?"; then
  step "In LaunchDarkly, find flag: dashboard-oauth-bearer-graphql"
  step "Target your team (include), and save."
  pause "Press Enter once the flag targets your team"
else
  note "skipped — project list + feature-flag list will report AUTH (expected)."
fi
pause "Press Enter to continue"

# ── Stage 6: run the parity smoke test ───────────────────────────────────
stage "Run the parity smoke test"
say "Loading WORKOS_API_KEY + PARITY_ENV_ID from .env.local, then running:"
say "  bun run scripts/parity-smoke.ts"
say ""
say "Each row prints PASS / FAIL / AUTH. Quick key:"
note "CONTROL   REST on both branches → strict shape+data parity. A FAIL here"
note "          usually means env/auth misalignment, so MIGRATED results below"
note "          aren't trustworthy yet."
note "MIGRATED  moved to GraphQL → DATA parity only (shapes differ by design)."
note "          FAIL = an entity's id/primary attribute differs between sides."
note "AUTH      exit 4 — session/flag issue, not a data divergence."
note "NEW       branch-only → just exit 0 + valid JSON."
say ""
pause "Press Enter to run the test"
set -a; # shellcheck disable=SC1090
source "$ENV_FILE"; set +a
bun run scripts/parity-smoke.ts || true
say ""
note "Exit 0 = all pass · 1 = at least one FAIL · AUTH rows are reported separately."
pause "Press Enter to finish"

# ──────────────────────────────────────────────────────────────────────────

finish
